### ISSUE TITLE
Memory corruption with multiple detectors

### ISSUE THREAD

**Issue by sergebb** [duaneloh/Dragonfly#12]
> recon_emc.c:93
> struct detector *orig_det = calloc(1, sizeof(struct detector)) ;
> copy_detector(det, orig_det) ;

**orig_det** have allocated memory for one detector but **orig_det[0].num_det** contain actual number of detectors.

It cause memory corruption here:
> recon_emc.c:137
> free_detector(orig_det) ;

**Comment by kartikayyer** [comment]
Good catch. 

The whole multiple detector mode is experimental, and the radius-based coupling (which is even more experimental) of `num_div` and the relevant pixel mask works only for a single detector right now. 

I will add a fix so that it does not crash here, but it is clear that a little more work is needed to properly integrate and test multiple detectors.
